[workspace]
authors = ["Etienne Mathier <etienne@mathier.ch>"]
channels = ["conda-forge"]
name = "optiboard"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
sl = "streamlit run streamlit/Hello.py"
mlf = "cd /Users/etienne/optiboard/ml/mlflow; mlflow server"

[dependencies]
marimo = ">=0.23.8,<0.24"
numpy = ">=2.4.6,<3"
scikit-learn = ">=1.8.0,<2"
xgboost = ">=3.2.0,<4"
matplotlib = ">=3.10.9,<4"
plotly = ">=6.6.0,<7"
polars = ">=1.41.2,<2"
google-cloud-bigquery = ">=3.41.0,<4"
streamlit = ">=1.58.0,<2"
duckdb = ">=1.5.3,<2"
dayplot = ">=0.5.1,<0.6"
mlflow = ">=3.13.0,<4"
shap = ">=0.51.0,<0.52"
